{{- $auth := (default (dict) .Values.airflow.auth) -}}
{{- if and (default false $auth.createUser) (not (default "" $auth.existingSecret)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "airflow.fullname" . }}-admin-user
  labels:
    app: {{ include "airflow.labels.app" . }}
    chart: {{ include "airflow.labels.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  username: {{ (default "admin" $auth.username) | b64enc | quote }}
  {{- $existing := (lookup "v1" "Secret" .Release.Namespace (printf "%s-admin-user" (include "airflow.fullname" .))) }}
  {{- if and $existing (hasKey $existing.data "password") }}
  password: {{ index $existing.data "password" | quote }}
  {{- else }}
  password: {{ (default (randAlphaNum 16) $auth.password) | b64enc | quote }}
  {{- end }}
  firstname: {{ (default "Airflow" $auth.firstName) | b64enc | quote }}
  lastname: {{ (default "Admin" $auth.lastName) | b64enc | quote }}
  email: {{ (default "admin@example.com" $auth.email) | b64enc | quote }}
{{- end }}


