apiVersion: v2
description: Airflow Helm Chart (User Community) - the standard way to deploy Apache Airflow on Kubernetes with Helm
name: airflow
version: 9.0.0
appVersion: 3.0.4
icon: https://avatars.githubusercontent.com/u/71061241
home: https://github.com/airflow-helm/charts/tree/main/charts/airflow
maintainers:
  - name: thesuperzapper
    url: https://github.com/thesuperzapper
sources:
  - https://github.com/airflow-helm/charts/tree/main/charts/airflow
keywords:
  - airflow
  - dag
  - workflow
dependencies:
  - name: postgres
    version: 0.4.7
    repository: https://groundhog2k.github.io/helm-charts/
    condition: postgres.enabled
  - name: redis
    version: 0.5.2
    repository: https://groundhog2k.github.io/helm-charts/
    condition: redis.enabled
